### ISSUE TITLE
Sample IOS not working

### ISSUE THREAD

**Issue by aperdec** [Fulanko/reactxp-map#2]
Hey just wondering if the iOS sample project is working. If you do could you please share what is required to make it work. Thanks

**Comment by Fulanko** [comment]
Is there a specific problem that you are facing?

Did you follow the react-native-maps setup steps from here:
https://github.com/react-community/react-native-maps/blob/master/docs/installation.md

**Comment by aperdec** [comment]
What you posted actually helped. My issue was when building the system could not find the library -lreact-native-maps. I did not realize that there was a  .xcworkspace and I was using the .xcodeproj. The instructions you posted was the first place I saw them mention the difference. Thanks for your help.
